SELECT TOP 10 ID_ENDERECO
	,ID_TP_LOGRADOURO
	,DS_LOGRADOURO
	,NR_IMOVEL
	,ID_LOCALIDADE
	,DS_COMPLEM_ENDERECO
	,DS_COMPLEM_ENDERECO2
	,NR_CEP
	,DS_BAIRRO
	
/*	
	,CD_SECAO_SERVICO
	,NR_TELEFONE1
	,NR_TELEFONE2
	,DS_END_ELETRONICO
	,ID_SISTEMA_FONTE
	,CD_ENDERECO
	,ID_LOGRADOURO
	,ID_RUN
	,ID_ENDERECO_UNICO
	,CD_ENDERECO_SIEBEL
	,NM_REDE
*/
FROM PW_VIEDB.ENDERECO_FISICO
