select  top 10
--e.ID_LOCALIDADE as loc,
b.ID_UNICO_SISTEMA_LEGADO as NRC,
e.ID_PRODUTO_COMERCIAL as Tel,
a.DT_VNCMO_FTRA_TLFNA as Venc,
c.NU_NOTA_FSCL_TLFNA as num_Fat,
--d.CD_SUBTP_PRODUTO_COMERCIAL as classe,
--g.ID_GRUPO_SEGMENTO_CLIENTE as seg,
--a.ID_CICLO,
--a.ID_SISTEMA_FONTE as sistema,
-- a.ID_PC_PRODUTO_COMERCIAL,
a.valor
from
                (select ID_FTRA, ID_PC_PRODUTO_COMERCIAL, ID_CICLO, DT_MES_FTRA, DT_VNCMO_FTRA_TLFNA, 
ID_SISTEMA_FONTE, ID_SUBSEGMENTO_CLIENTE,ID_LOCALIDADE, ID_SUBTP_PRODUTO_COMERCIAL,
sum(VL_DBITO_ITEM) as valor from PW_VIEDB.V245_ITEM_FTRA 
where ID_SISTEMA_FONTE=2
/*and ID_PC_PRODUTO_COMERCIAL = 100879586684 */
group by 1,2,3,4,5,6,7,8,9) as A
left join
                PW_VIEDB.PARQUE_CONTRATADO as B
on a.ID_PC_PRODUTO_COMERCIAL = b.ID_PC_PRODUTO_COMERCIAL 
left join
                (select ID_FTRA,DT_MES_FTRA,ID_PC_PRODUTO_COMERCIAL,NU_NOTA_FSCL_TLFNA,
                count(*) as qt   from PW_VIEDB.V244_FTRA  /*where  ID_PC_PRODUTO_COMERCIAL = 100879586684*/ group by 1,2,3,4) as C
on a.ID_PC_PRODUTO_COMERCIAL = c.ID_PC_PRODUTO_COMERCIAL
and a.ID_FTRA = c.ID_FTRA
left join
                PW_VIEDB.PARQUE_CONTRATADO_hist as e
on a.ID_PC_PRODUTO_COMERCIAL = e.ID_PC_PRODUTO_COMERCIAL
and e.dt_fim = '2100-12-31'
left join
                SUBTIPO_PRODUTO_COMERCIAL as D
on a.ID_SUBTP_PRODUTO_COMERCIAL = d.ID_SUBTP_PRODUTO_COMERCIAL
left join
                SUBSEGMENTO_CLIENTE as F
on a.ID_SUBSEGMENTO_CLIENTE = f.ID_SUBSEGMENTO_CLIENTE
left join
                SEGMENTO_CLIENTE as G
on f.ID_SEGMENTO_CLIENTE = g.ID_SEGMENTO_CLIENTE