declare @ID int 
exec [APP_WEB].[PRC_CENARIO_testes] 
 '(ID_ANALISTA = ''110'' or ID_ANALISTA_TMP = ''110'') and RAIZ_GRUPO = ''4032319931'' '
 ,110
 ,4032319931 
 ,@ID OUTPUT 

SELECT @ID as ID_FILE 


INSERT INTO OPENROWSET('Microsoft.ACE.OLEDB.12.0','Excel 12.0 Xml;HDR=YES;IMEX=0;Database=\\172.16.0.11\siscob\CENARIO\4032319931_CENARIO.xlsm','SELECT * FROM [Dados$]') 
SELECT PROCV
	,ID
	,CONVERT(VARCHAR(255), NOME_ANALISTA) as NOME_ANALISTA 
	,CONVERT(VARCHAR(255), NOME_ANALISTA_TMP) as NOME_ANALISTA_TMP 
	,FEEDBACK
	,AREA_OFENSORA
	,TIPO_PAGTO
	,DT_PAGTO
	,REPLACE(CONVERT(VARCHAR(20), VALOR_PAGTO), '.', ',') as VALOR_PAGTO
	,DT_AJUSTE
	,REPLACE(CONVERT(VARCHAR(20), VALOR_AJUSTADO), '.', ',') as VALOR_AJUSTADO
	,CONVERT(VARCHAR(255), RESUMO_EXECUTIVO_ACAO) as RESUMO_EXECUTIVO_ACAO
	,CONVERT(VARCHAR(255), RESUMO_EXECUTIVO_PROBLEMA) as RESUMO_EXECUTIVO_PROBLEMA
	,CONVERT(VARCHAR(255), HISTORICO_DETALHADO) as HISTORICO_DETALHADO
	,DT_FOLLOW_UP
	,DT_ENCERRAMENTO
	,DT_CONTATO
	,CONVERT(VARCHAR(255), RESPONSAVEL) as RESPONSAVEL
	,FAIXA_FORNECEDOR
	,FAIXA_FECHO
	,FAIXA_ARRECADA_INICIAL
	,FAIXA_ARRECADA_ATUAL
	,RAIZ_GRUPO
	,GRUPO
	,RAIZ
	,CNPJ
	,NOME
	,NOME_CLIENTE
	,TIPO
	,EMPRESA
	,CONTA
	,TEL
	,LOCAL
	,TERMINAL
	,DV
	,NRC
	,CLASSERV
	,TITULO
	,FILIAL
	,LJ_CLI
	,COD_CLI
	,DOCUMENTO_SAP
	,DOC_FAT
	,N_DOC_DE_PARA_ATLYS
	,NOTA_FISCAL
	,VENC_ATUAL
	,VENC_ORIGINAL
	,DT_PROCESS
	,ANOMES
	,DIA_VENCIMENTO_LOTE
	,NUMERO_LOTE
	,REPLACE(CONVERT(VARCHAR(20), VALOR_LOTE), '.', ',') as VALOR_LOTE
	,REPLACE(CONVERT(VARCHAR(20), SALDO_CAR_26), '.', ',') as SALDO_CAR_26
	,REPLACE(CONVERT(VARCHAR(20), SALDO_CAR_05), '.', ',') as SALDO_CAR_05
	,REPLACE(CONVERT(VARCHAR(20), SALDO_CAR_14), '.', ',') as SALDO_CAR_14
	,REPLACE(CONVERT(VARCHAR(20), SALDO_CAR_21), '.', ',') as SALDO_CAR_21
	,REPLACE(CONVERT(VARCHAR(20), SALDO_CAR_25), '.', ',') as SALDO_CAR_25
	,REPLACE(CONVERT(VARCHAR(20), SALDO_TOTAL), '.', ',') as SALDO_TOTAL
	,REPLACE(CONVERT(VARCHAR(20), SOMA_FXE_PDD_26), '.', ',') as SOMA_FXE_PDD_26
	,REPLACE(CONVERT(VARCHAR(20), SOMA_FXE_PDD_05), '.', ',') as SOMA_FXE_PDD_05
	,REPLACE(CONVERT(VARCHAR(20), SOMA_FXE_PDD_14), '.', ',') as SOMA_FXE_PDD_14
	,REPLACE(CONVERT(VARCHAR(20), SOMA_FXE_PDD_21), '.', ',') as SOMA_FXE_PDD_21
	,REPLACE(CONVERT(VARCHAR(20), SOMA_FXE_PDD_25), '.', ',') as SOMA_FXE_PDD_25
	,REPLACE(CONVERT(VARCHAR(20), VALOR_PAGAMENTO), '.', ',') as VALOR_PAGAMENTO
	,REPLACE(CONVERT(VARCHAR(20), VALOR_AJUSTE), '.', ',') as VALOR_AJUSTE
	,REPLACE(CONVERT(VARCHAR(20), SALDO_ATUAL), '.', ',') as SALDO_ATUAL
	,CICLO
	,UF
	,STATUS
	,CLASSE
	,SEGMENTO_GERENCIA
	,GN
	,GV
	,DIRETOR
	,ANALISTA_TLF_VIVO
	,INTRAGOV
	,INTERCOMPANY
	,FEEDBACK_00
	,FEEDBACK_01
	,FEEDBACK_02
	,FEEDBACK_03
	,FEEDBACK_04
	,FEEDBACK_05
	,PENDENTE_ID_ANALISE_CONTA
	,PENDENTE_DATA_ANALISE_CONTA
	,CONCLUIDO_ID_ANALISE_CONTA
	,CONCLUIDO_DATA_ANALISE_CONTA
	,REABERTO_ID_ANALISE_CONTA
	,REABERTO_DATA_ANALISE_CONTA
	,QTD_REG_AGRUPADO
	,DT_ULT_ALTERACAO
	,CONVERT(VARCHAR(255), USUARIO_ATUALIZACAO) as USUARIO_ATUALIZACAO
	,ID_ANALISTA
	,ID_ANALISTA_TMP
	,AREA_ATUACAO
	,TASK_FORCE
	,SEG_DESCR
	,PARCELAMENTO
	,ESCALATION
FROM [APP_EXCEL].[VW_CONSUMO_CONSOLIDADO_ANALISTA]
WHERE (
		ID_ANALISTA = '110'
		OR ID_ANALISTA_TMP = '110'
		)
	AND RAIZ_GRUPO = '4032319931'
