DECLARE @FILE_PATH				VARCHAR(1000); SET @FILE_PATH				= (SELECT TOP 1 [DESCRICAO] AS 'FILE_PATH' FROM [DB_SISCOB].[ADM].[TB_APP_CONTROLE] WHERE [TIPO] = 'PAGTO_AJUSTE' ORDER BY [ID] DESC);
DECLARE @FILE_NAME				VARCHAR(1000); SET @FILE_NAME				= (SELECT TOP 1 [DESCRICAO_02] AS 'FILE_NAME' FROM [DB_SISCOB].[ADM].[TB_APP_CONTROLE] WHERE [TIPO] = 'PAGTO_AJUSTE' ORDER BY [ID] DESC);

DECLARE @TMP					NVARCHAR(1000); SET @TMP						= 'Excel 12.0;Database='+ @FILE_PATH + @FILE_NAME

DECLARE @SQL VARCHAR(8000) 


SET @SQL = '
INSERT INTO [TRANSITO].[tmp_PAGTO_AJUSTE]
           ([CONTA]
           ,[DT_CORTE]
           ,[VALOR_AJUSTE]
           ,[VALOR_PAGTO]
           ,[dt_atrib]
           )
SELECT 
	[CONTA]
	,convert(datetime,[DT_CORTE],103)
	,[VALOR_AJUSTE]
	,[VALOR_PAGTO]
	,convert(datetime,[dt_atrib],103) 
FROM 
OPENROWSET(''Microsoft.ACE.OLEDB.12.0'','''+ @TMP+''' , [dados$])'


EXEC( @SQL)


--SELECT * FROM [TRANSITO].[tmp_PAGTO_AJUSTE]
--DELETE FROM [TRANSITO].[tmp_PAGTO_AJUSTE]
