SELECT 
    [SEG_DESCR] AS [SEG_DESCR]
    ,[FORNECEDOR] AS [FORNECEDOR]
    ,sum([SALDO_CAR]) AS SOMA_SALDO_CAR
FROM 
    [DB_SISCOB].[FILE_CAR].[TB_TRATAMENTO_FIXA_WEB]
WHERE 
    [OK] = 1
GROUP BY 
    [SEG_DESCR]
    ,[FORNECEDOR]
