SELECT [ID]
,[TIME_STAMP]
,[OBS]
      ,[ID_CONSOLIDADO]
	  ,[RESPONSAVEL]
      ,[RESUMO_EXECUTIVO]
      ,[HISTORICO_DETALHADO]
      ,[HD_ACUMULADO]
      ,[STATUS]
      ,[RE_PROBLEMA]
      ,[RE_ACAO]
	  ,[ID_SEMANA]
      ,[ID_FOCO_FEEDBACK]
      ,[ID_TIPO_PAGAMENTO]
      ,[ID_ANALISTA]
       ,[DT_FOLLOW]
      ,[DT_CONTATO]
      ,[DT_ENCERRAMENTO]
      ,[DT_ABERTURA]
      ,[DT_AJUSTE]
      ,[DT_PAGAMENTO]
      ,[VALOR_PAGO]
      ,[VALOR_AJUSTE]
      ,[LOTE]
      ,[GESTAO_CONTA]
      ,[CBPM]
      ,[ID_PORTAL_DEMANDA]
      ,[NUMERO_BOLETO]
      ,[DATA_EMISSAO_BOLETO]
      ,[ID_GESTAO_CONTA]
  FROM [DB_SISCOB_HML].[CONSOLIDADO].[TB_HISTORICO] 
  WHERE 
	ID_CONSOLIDADO in (SELECT ID FROM [DB_SISCOB].[CONSOLIDADO].[TB_CONSOLIDADO] WHERE RAIZ_GRUPO = '4060701190')
	--ID_CONSOLIDADO='6623600'
	
  ORDER BY ID DESC



  SELECT count(*)
  FROM [DB_SISCOB_HML].[CONSOLIDADO].[TB_HISTORICO] 
  where
  ID_CONSOLIDADO in (SELECT ID FROM [DB_SISCOB].[CONSOLIDADO].[TB_CONSOLIDADO] WHERE RAIZ_GRUPO = '4060701190')
  and
  [TIME_STAMP]='2017-02-20 16:23:34.293'
