




-- ####################################################################################

-- ARQUIVOS DE CENARIOS
SELECT * FROM [DB_SISCOB].[APP_WEB].[TBL_ARQUIVOS_TRANSITO_CENARIOS]

ALTER TABLE [DB_SISCOB].[APP_WEB].[TBL_ARQUIVOS_TRANSITO_CENARIOS] ADD QUERY_RESUMO VARCHAR(MAX)

delete from [DB_SISCOB].[APP_WEB].[TBL_ARQUIVOS_TRANSITO_CENARIOS] where [id] in (SELECT [ID] FROM [DB_SISCOB].[APP_WEB].[TBL_ARQUIVOS_TRANSITO_CENARIOS] where [id] NOT IN (1))


-- USUÁRIOS
SELECT * FROM [DB_SISCOB].[APP_WEB].[TBL_USUARIOS] where [fname] like '%laris%'



--DECLARE @TESTE VARCHAR(100);SET @TESTE=  LEFT('\\172.16.0.11\siscob\CENARIO/',LEN('\\172.16.0.11\siscob\CENARIO/')-1) +'\';PRINT @TESTE



-- ####################################################################################


USE [DB_SISCOB]
GO

DECLARE	@return_value int,
		@ID_FILE int,
		@QUERY_WHERE VARCHAR(200)

		SET @QUERY_WHERE = REPLACE('(ID_ANALISTA = ''86'' or ID_ANALISTA_TMP = ''86'') and RAIZ_GRUPO = ''4002429144'' ','''','')
		PRINT @QUERY_WHERE

EXEC	@return_value = [APP_WEB].[PRC_CENARIO]
		@QUERY_WHERE = @QUERY_WHERE,
		@ANALISTA = N'86',
		@ID_FILE = @ID_FILE OUTPUT

SELECT	@ID_FILE as N'@ID_FILE'

SELECT	'Return Value' = @return_value

GO


declare @ID int exec [APP_WEB].[PRC_CENARIO] '(ID_ANALISTA = ''86'' or ID_ANALISTA_TMP = ''86'') and RAIZ_GRUPO = ''4002429144'' ', 86, @ID OUTPUT SELECT @ID as ID_FILE 


--SET @SQL = 'SELECT PROCV, ID, NOME_ANALISTA COLLATE sql_latin1_general_cp1251_ci_as NOME_ANALISTA , NOME_ANALISTA_TMP,FEEDBACK,AREA_OFENSORA,TIPO_PAGTO,DT_PAGTO,VALOR_PAGTO,DT_AJUSTE,VALOR_AJUSTADO, RESUMO_EXECUTIVO_ACAO,RESUMO_EXECUTIVO_PROBLEMA,'' AS HISTORICO_DETALHADO, convert(varchar,DT_FOLLOW_UP,103) as DT_FOLLOW_UP,convert(varchar,DT_ENCERRAMENTO,103) as DT_ENCERRAMENTO, convert(varchar,DT_CONTATO,103) as DT_CONTATO,RESPONSAVEL,FAIXA_FORNECEDOR,FAIXA_FECHO,FAIXA_ARRECADA_INICIAL,FAIXA_ARRECADA_ATUAL,RAIZ_GRUPO,GRUPO,RAIZ,CNPJ,NOME,NOME_CLIENTE, TIPO COLLATE sql_latin1_general_cp1251_ci_as TIPO,EMPRESA,CONTA,TEL,LOCAL,TERMINAL,DV,NRC,CLASSERV,TITULO,FILIAL,LJ_CLI,COD_CLI,DOCUMENTO_SAP,DOC_FAT,N_DOC_DE_PARA_ATLYS,NOTA_FISCAL,convert(varchar,VENC_ATUAL,103) as VENC_ATUAL, convert(varchar,VENC_ORIGINAL,103) as VENC_ORIGINAL,convert(varchar,DT_PROCESS,103) as DT_PROCESS,ANOMES,DIA_VENCIMENTO_LOTE,NUMERO_LOTE,VALOR_LOTE,SALDO_CAR_26,SALDO_CAR_05,SALDO_CAR_14, SALDO_CAR_21,SALDO_CAR_25,SALDO_TOTAL,SOMA_FXE_PDD_26,SOMA_FXE_PDD_05,SOMA_FXE_PDD_14,SOMA_FXE_PDD_21,SOMA_FXE_PDD_25,VALOR_PAGAMENTO,VALOR_AJUSTE,SALDO_ATUAL,CICLO,UF,STATUS,CLASSE, SEGMENTO_GERENCIA,GN,GV,DIRETOR,ANALISTA_TLF_VIVO,INTRAGOV,INTERCOMPANY,FEEDBACK_00,FEEDBACK_01,FEEDBACK_02,FEEDBACK_03,FEEDBACK_04,FEEDBACK_05,PENDENTE_ID_ANALISE_CONTA,PENDENTE_DATA_ANALISE_CONTA, CONCLUIDO_ID_ANALISE_CONTA,CONCLUIDO_DATA_ANALISE_CONTA,REABERTO_ID_ANALISE_CONTA,REABERTO_DATA_ANALISE_CONTA,QTD_REG_AGRUPADO,convert(varchar,DT_ULT_ALTERACAO,103) as DT_ULT_ALTERACAO,USUARIO_ATUALIZACAO, ID_ANALISTA,ID_ANALISTA_TMP,AREA_ATUACAO,TASK_FORCE,SEG_DESCR,PARCELAMENTO,ESCALATION FROM [APP_EXCEL].[VW_CONSUMO_CONSOLIDADO_ANALISTA] where (ID_ANALISTA = ''110'' or ID_ANALISTA_TMP = ''110'') and RAIZ_GRUPO = ''4030306294'' '
--SET @SQL = 'SELECT PROCV, ID, NOME_ANALISTA COLLATE sql_latin1_general_cp1251_ci_as NOME_ANALISTA , NOME_ANALISTA_TMP,FEEDBACK,AREA_OFENSORA,TIPO_PAGTO,DT_PAGTO,VALOR_PAGTO,DT_AJUSTE,VALOR_AJUSTADO, RESUMO_EXECUTIVO_ACAO,RESUMO_EXECUTIVO_PROBLEMA,HISTORICO_DETALHADO, convert(varchar,DT_FOLLOW_UP,103) as DT_FOLLOW_UP,convert(varchar,DT_ENCERRAMENTO,103) as DT_ENCERRAMENTO, convert(varchar,DT_CONTATO,103) as DT_CONTATO,RESPONSAVEL,FAIXA_FORNECEDOR,FAIXA_FECHO,FAIXA_ARRECADA_INICIAL,FAIXA_ARRECADA_ATUAL,RAIZ_GRUPO,GRUPO,RAIZ,CNPJ,NOME,NOME_CLIENTE, TIPO COLLATE sql_latin1_general_cp1251_ci_as TIPO,EMPRESA,CONTA,TEL,LOCAL,TERMINAL,DV,NRC,CLASSERV,TITULO,FILIAL,LJ_CLI,COD_CLI,DOCUMENTO_SAP,DOC_FAT,N_DOC_DE_PARA_ATLYS,NOTA_FISCAL,convert(varchar,VENC_ATUAL,103) as VENC_ATUAL, convert(varchar,VENC_ORIGINAL,103) as VENC_ORIGINAL,convert(varchar,DT_PROCESS,103) as DT_PROCESS,ANOMES,DIA_VENCIMENTO_LOTE,NUMERO_LOTE,VALOR_LOTE,SALDO_CAR_26,SALDO_CAR_05,SALDO_CAR_14, SALDO_CAR_21,SALDO_CAR_25,SALDO_TOTAL,SOMA_FXE_PDD_26,SOMA_FXE_PDD_05,SOMA_FXE_PDD_14,SOMA_FXE_PDD_21,SOMA_FXE_PDD_25,VALOR_PAGAMENTO,VALOR_AJUSTE,SALDO_ATUAL,CICLO,UF,STATUS,CLASSE, SEGMENTO_GERENCIA,GN,GV,DIRETOR,ANALISTA_TLF_VIVO,INTRAGOV,INTERCOMPANY,FEEDBACK_00,FEEDBACK_01,FEEDBACK_02,FEEDBACK_03,FEEDBACK_04,FEEDBACK_05,PENDENTE_ID_ANALISE_CONTA,PENDENTE_DATA_ANALISE_CONTA, CONCLUIDO_ID_ANALISE_CONTA,CONCLUIDO_DATA_ANALISE_CONTA,REABERTO_ID_ANALISE_CONTA,REABERTO_DATA_ANALISE_CONTA,QTD_REG_AGRUPADO,convert(varchar,DT_ULT_ALTERACAO,103) as DT_ULT_ALTERACAO,USUARIO_ATUALIZACAO, ID_ANALISTA,ID_ANALISTA_TMP,AREA_ATUACAO,TASK_FORCE,SEG_DESCR,PARCELAMENTO,ESCALATION FROM [APP_EXCEL].[VW_CONSUMO_CONSOLIDADO_ANALISTA] where (ID_ANALISTA = ''110'' or ID_ANALISTA_TMP = ''110'') and RAIZ_GRUPO = ''4030306294'' '
