/****** Script for SelectTopNRows command from SSMS  ******/
SELECT *
  FROM  [DB_SISCOB].[APP_WEB].[TBL_ARQUIVOS_TRANSITO_SEGMENTO] 

  --ALTER TABLE [DB_SISCOB].[APP_WEB].[TBL_ARQUIVOS_TRANSITO_SEGMENTO] DROP COLUMN  [HISTORICO] 


   --ALTER TABLE [DB_SISCOB].[APP_WEB].[TBL_ARQUIVOS_TRANSITO_SEGMENTO] ADD HISTORICO BIT NOT NULL DEFAULT 0

--SELECT * FROM SYSOBJECTS WHERE NAME = 'DF__TBL_ARQUI__HISTO__274FAE79'

--ALTER TABLE [DB_SISCOB].[APP_WEB].[TBL_ARQUIVOS_TRANSITO_SEGMENTO] DROP CONSTRAINT DF__TBL_ARQUI__HISTO__274FAE79