select * 
into [DB_SISCOB].[BKP].[TB_MIS_VPE_FIXA_TUDO]
from (
select * FROM [DB_SISCOB].[APP_EXCEL].[VW_RELATORIO_WEB_MIS_VPE_FIXA_NAO]
union
select * FROM [DB_SISCOB].[APP_EXCEL].[VW_RELATORIO_WEB_MIS_VPE_FIXA_NAO__VPE]
union
select * FROM [DB_SISCOB].[APP_EXCEL].[VW_RELATORIO_WEB_MIS_VPE_FIXA_NAO__VPE-GOV]
union
select * FROM [DB_SISCOB].[APP_EXCEL].[VW_RELATORIO_WEB_MIS_VPE_FIXA_SIM]
) tmp