DROP TABLE [DB_SISCOB].[TRANSITO].[HISTORICO_ACUMULADO]
SELECT 
ID_CONSOLIDADO
,HD = STUFF(
		(SELECT
					'|' + isnull(HISTORICO_DETALHADO, '' )
		FROM [DB_SISCOB].[CONSOLIDADO].[TB_HISTORICO]
		where h.ID_CONSOLIDADO  = ID_CONSOLIDADO
		ORDER BY ID DESC 
		FOR XML PATH ('')), 1, 1, ''
		) 
INTO [DB_SISCOB].[TRANSITO].[HISTORICO_ACUMULADO]
FROM
[DB_SISCOB].[CONSOLIDADO].[TB_HISTORICO] H
--WHERE h.ID_CONSOLIDADO  in (SELECT ID FROM [DB_SISCOB].[CONSOLIDADO].[TB_CONSOLIDADO] WHERE RAIZ_GRUPO = '04127856')
GROUP BY ID_CONSOLIDADO

/*** ATUALIZAÇÃO ***/
UPDATE tmp
set 
tmp.HD_ACUMULADO = hst.HD
from  [DB_SISCOB].[CONSOLIDADO].[TB_HISTORICO] tmp
INNER JOIN [DB_SISCOB].[CONSOLIDADO].[TB_CONSUMO_SISCOB] cs ON CS.ID_HISTORICO_ATUAL = tmp.ID
INNER JOIN [DB_SISCOB].[TRANSITO].[HISTORICO_ACUMULADO] hst on hst.ID_CONSOLIDADO = tmp.ID_CONSOLIDADO
