/****** ADM - LOCALIZAR TROCA DE SEGUIMENTO  ******/
-- DROP TABLE #TMP
SELECT PROCV
	,ID_TIPO
	,SEG_DESCR
	,COUNT(1) AS CONTAR
INTO #TMP
FROM [DB_SISCOB].[CONSOLIDADO].[TB_CONSOLIDADO]
WHERE ID_TIPO = 1 -- TIPO DE SEGUIMENTO
	AND ID_PERIODO = 12 -- ID DO PERIODO
	AND DTCORTE = '2017-02-28' -- DATA DE CORTE
GROUP BY PROCV
	,ID_TIPO
	,SEG_DESCR;


SELECT *
FROM #TMP
WHERE contar > 1;


SELECT MAX(ID_CONSOLIDADO) AS ID_CONSOLIDADO
INTO #TMP_SELECAO
FROM [DB_SISCOB].[CONSOLIDADO].[TB_DADOS_E_VALORES] V
WHERE PROCV IN (
		SELECT PROCV
		FROM #TMP
		WHERE CONTAR > 1
		)
	AND ID_STATUS_CAR = 41
GROUP BY V.PROCV;


SELECT *
FROM [DB_SISCOB].[CONSOLIDADO].[TB_DADOS_E_VALORES]
WHERE ID_CONSOLIDADO IN (
		SELECT *
		FROM #TMP_SELECAO
		)
	AND ID_STATUS_CAR = 41;


--DELETE FROM [DB_SISCOB].[CONSOLIDADO].[TB_DADOS_E_VALORES] WHERE ID_CONSOLIDADO IN (SELECT * FROM #TMP_SELECAO) AND ID_STATUS_CAR=41;


SELECT *
FROM [DB_SISCOB].[CONSOLIDADO].[TB_CONSOLIDADO]
WHERE ID IN (
		SELECT *
		FROM #TMP_SELECAO
		)
	AND ID_PERIODO = 12;


UPDATE [DB_SISCOB].[CONSOLIDADO].[TB_CONSOLIDADO]
SET ID_PERIODO = 1
WHERE ID IN (
		SELECT *
		FROM #TMP_SELECAO
		)
	AND ID_PERIODO = 12;


SELECT b.*
FROM [DB_SISCOB].[CONSOLIDADO].[TB_CONSOLIDADO] c
INNER JOIN [DB_SISCOB].[CONSOLIDADO].[TB_DADOS_E_VALORES] v ON v.ID_CONSOLIDADO = c.ID
	AND v.ID_STATUS_CAR = 41
INNER JOIN [DB_SISCOB].[BKP].[20170313_1833_TB_TRATAMENTO_FIXA_WEB] b ON c.PROCV = b.procv
	AND b.ok = 1
WHERE c.ID_SEGMENTO = 1
	AND c.ID_TIPO = 1
	AND c.SALDO_CAR <> b.SALDO_CAR;
