USE [DB_SISCOB]
GO

/****** Object:  Index [PK_TB_CONSOLIDADO]    Script Date: 11/26/2016 12:17:59 AM ******/
CREATE TABLE [CONSOLIDADO].[TB_CONSOLIDADO] ADD  CONSTRAINT [PK_TB_CONSOLIDADO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO




ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO]  WITH CHECK ADD  CONSTRAINT [FK_TB_CONSOLIDADO_ID_AGING_ARRECADA] FOREIGN KEY([ID_NV_FX_ARRECADA])
REFERENCES [AUXILIAR].[TB_DESCRICAO_AGING] ([ID])
GO

ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO] CHECK CONSTRAINT [FK_TB_CONSOLIDADO_ID_AGING_ARRECADA]
GO



ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO]  WITH CHECK ADD  CONSTRAINT [FK_TB_CONSOLIDADO_ID_AGING_FECHO] FOREIGN KEY([ID_NV_FX_FECHO])
REFERENCES [AUXILIAR].[TB_DESCRICAO_AGING] ([ID])
GO

ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO] CHECK CONSTRAINT [FK_TB_CONSOLIDADO_ID_AGING_FECHO]
GO



ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO]  WITH CHECK ADD  CONSTRAINT [FK_TB_CONSOLIDADO_ID_AGING_FORNECE] FOREIGN KEY([ID_NV_FX_FORNECE])
REFERENCES [AUXILIAR].[TB_DESCRICAO_AGING] ([ID])
GO

ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO] CHECK CONSTRAINT [FK_TB_CONSOLIDADO_ID_AGING_FORNECE]
GO



ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO]  WITH CHECK ADD  CONSTRAINT [FK_TB_CONSOLIDADO_ID_PERIODO] FOREIGN KEY([ID_PERIODO])
REFERENCES [AUXILIAR].[TB_PERIODO] ([ID])
GO

ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO] CHECK CONSTRAINT [FK_TB_CONSOLIDADO_ID_PERIODO]
GO



ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO]  WITH CHECK ADD  CONSTRAINT [FK_TB_CONSOLIDADO_ID_SEGMENTO] FOREIGN KEY([ID_SEGMENTO])
REFERENCES [AUXILIAR].[TB_SEGMENTO] ([ID])
GO

ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO] CHECK CONSTRAINT [FK_TB_CONSOLIDADO_ID_SEGMENTO]
GO



ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO]  WITH CHECK ADD  CONSTRAINT [FK_TB_CONSOLIDADO_ID_TIPO] FOREIGN KEY([ID_TIPO])
REFERENCES [AUXILIAR].[TB_TIPO] ([ID])
GO

ALTER TABLE [CONSOLIDADO].[TB_CONSOLIDADO] CHECK CONSTRAINT [FK_TB_CONSOLIDADO_ID_TIPO]
GO


