DECLARE @ANALISTA				VARCHAR(500);	SET @ANALISTA = '94';
DECLARE @Cmd					VARCHAR(500);
DECLARE @FILE_QUERY				VARCHAR(MAX);	SET @FILE_QUERY			= (SELECT TOP 1 [DESCRICAO_03]	AS 'QUERY'				FROM [DB_SISCOB].[ADM].[TB_APP_CONTROLE] WHERE [TIPO] = 'ACORDO_QUERY' order by id desc);
DECLARE @FILE_MODEL_PATH		VARCHAR(1000);	SET @FILE_MODEL_PATH	= (SELECT TOP 1 [DESCRICAO] AS 'FILE_MODEL_PATH' FROM [DB_SISCOB].[ADM].[TB_APP_CONTROLE] WHERE [TIPO] = 'ACORDO_FILE_MODEL_PATH');
DECLARE @FILE_MODEL				VARCHAR(1000);	SET @FILE_MODEL			= (SELECT TOP 1 [DESCRICAO] AS 'FILE_MODEL' FROM [DB_SISCOB].[ADM].[TB_APP_CONTROLE] WHERE [TIPO] = 'ACORDO_FILE_MODEL');
DECLARE @FILE_EXIT				VARCHAR(1000);	SET @FILE_EXIT			= (SELECT TOP 1 [DESCRICAO_02] AS 'FILE_EXIT' FROM [DB_SISCOB].[ADM].[TB_APP_CONTROLE] WHERE [TIPO] = 'ACORDO_FILE_MODEL');
DECLARE @FILE_DOWNLOAD			VARCHAR(1000);	SET @FILE_DOWNLOAD		= (SELECT TOP 1 [DESCRICAO] AS 'FILE_DOWNLOAD' FROM [DB_SISCOB].[ADM].[TB_APP_CONTROLE] WHERE [TIPO] = 'ACORDO_APP');
DECLARE @FILE_APP				VARCHAR(1000);	SET @FILE_APP			= (SELECT TOP 1 [DESCRICAO]+[DESCRICAO_02] AS 'FILE_APP' FROM [DB_SISCOB].[ADM].[TB_APP_CONTROLE] WHERE [TIPO] = 'ACORDO_APP');
DECLARE @FILE_DOWNLOAD_TMP		VARCHAR(100);	SET @FILE_DOWNLOAD_TMP	= LEFT(@FILE_DOWNLOAD,LEN(@FILE_DOWNLOAD)-1) +'\'

--SET @FILE_APP = REPLACE(@FILE_APP,'\\172.16.0.11\siscob\ACORDO\','F:\SISCOB\ACORDO\')
SET @FILE_APP = REPLACE(@FILE_APP,'\\172.16.0.11\siscob\ACORDO\','\\172.16.0.13\z$\_siscob\new\')

SET @Cmd = @FILE_APP + ' ' + @ANALISTA;
PRINT @Cmd
EXEC xp_cmdshell @Cmd--, NO_OUTPUT