select count(*)
FROM [DB_SISCOB].[APP_EXCEL].[VW_RELATORIO_WEB_MIS_SEGMENTO_TODOS]
WHERE SEG_DESCR LIKE ('VPE%') AND TASK_FORCE = 'DEMAIS'


select *
into [DB_SISCOB].[TRANSITO].[TMP_RELATORIO_WEB_MIS_SEGMENTO_VPE_FIXA]
FROM [DB_SISCOB].[APP_EXCEL].[VW_RELATORIO_WEB_MIS_SEGMENTO_TODOS]
WHERE SEG_DESCR LIKE ('VPE%') AND TASK_FORCE = 'DEMAIS' and AREA_ATUACAO = 'fixa'

select *
into [DB_SISCOB].[TRANSITO].[TMP_RELATORIO_WEB_MIS_SEGMENTO_VPE_MOVEL]
FROM [DB_SISCOB].[APP_EXCEL].[VW_RELATORIO_WEB_MIS_SEGMENTO_TODOS]
WHERE SEG_DESCR LIKE ('VPE%') AND TASK_FORCE = 'DEMAIS' and AREA_ATUACAO = 'movel'