
/****** ADM - LOCALIZAR TROCA DE SEGUIMENTO  ******/
-- DROP TABLE #TMP


SELECT 

	 PROCV
	,ID_TIPO
	,SEG_DESCR
	,COUNT(1) AS CONTAR

INTO #TMP

FROM [DB_SISCOB].[CONSOLIDADO].[TB_CONSOLIDADO]

where 
		ID_TIPO = 1 				-- TIPO DE SEGUIMENTO
	AND ID_PERIODO = 12				-- ID DO PERIODO
	AND DTCORTE = '2017-02-28'		-- DATA DE CORTE

GROUP BY
	 PROCV
	,ID_TIPO
	,SEG_DESCR


SELECT * FROM #TMP where contar > 1 
