USE [DB_SISCOB]
GO

/****** Object:  View [APP_EXCEL].[VW_RELATORIO_WEB_MIS_SEGMENTO_VPE]    Script Date: 4/14/2017 6:54:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [APP_EXCEL].[VW_RELATORIO_WEB_MIS_SEGMENTO_VPE]
AS

SELECT PROCV
	,ID
	,NOME_ANALISTA
	,FEEDBACK
	,AREA_OFENSORA
	,TIPO_PAGTO
	,DT_PAGTO
	,VALOR_PAGTO
	,DT_AJUSTE
	,VALOR_AJUSTADO
	,convert(varchar(255),RESUMO_EXECUTIVO_PROBLEMA) as RESUMO_EXECUTIVO_PROBLEMA
	,convert(varchar(255),RESUMO_EXECUTIVO_ACAO) as RESUMO_EXECUTIVO_ACAO 
	,DT_FOLLOW_UP
	,DT_CONTATO
	,convert(varchar(255),RESPONSAVEL) as RESPONSAVEL
	,FAIXA_FORNECEDOR
	,FAIXA_FECHO
	,FAIXA_ARRECADA_INICIAL
	,FAIXA_ARRECADA_ATUAL
	,RAIZ_GRUPO
	,GRUPO
	,RAIZ
	,CNPJ
	,NOME
	,NOME_CLIENTE
	,TIPO
	,EMPRESA
	,CONTA
	,TEL
	,NRC
	,CLASSERV
	,TITULO
	,FILIAL
	,LJ_CLI
	,COD_CLI
	,DOCUMENTO_SAP
	,DOC_FAT
	,N_DOC_DE_PARA_ATLYS
	,NOTA_FISCAL
	,VENC_ATUAL
	,VENC_ORIGINAL
	,DT_PROCESS
	,ANOMES
	,DIA_VENCIMENTO_LOTE
	,NUMERO_LOTE
	,VALOR_LOTE
	,SALDO_CAR_26
	,SALDO_CAR_05
	,SALDO_CAR_30
	,SALDO_CAR_14
	,SALDO_CAR_21
	,SALDO_CAR_25
	,SALDO_TOTAL
	,VALOR_PAGAMENTO
	,VALOR_AJUSTE
	,dt_atrib
	,SALDO_ATUAL
	,CICLO
	,UF
	,STATUS
	,CLASSE
	,SEGMENTO_GERENCIA
	,GN
	,GV
	,DIRETOR
	,ANALISTA_TLF_VIVO
	,INTRAGOV
	,INTERCOMPANY
	,PENDENTE_ID_ANALISE_CONTA
	,PENDENTE_DATA_ANALISE_CONTA
	,CONCLUIDO_ID_ANALISE_CONTA
	,CONCLUIDO_DATA_ANALISE_CONTA
	,REABERTO_ID_ANALISE_CONTA
	,REABERTO_DATA_ANALISE_CONTA
	,AREA_ATUACAO
	,TASK_FORCE
	,SEG_DESCR
	,PARCELAMENTO
	,CONTA_BONUS
	,FORNECEDOR
	,REGRA_PDD
	,PROVISAO
	,SITUACAO_SERVICO
	,SALDO_FX_ENT_26
	,SALDO_PDD_26
	,SALDO_FX_ENT_30
	,SALDO_PDD_30
	,SALDO_FX_ENT_05
	,SALDO_PDD_05
	,SALDO_FX_ENT_14
	,SALDO_PDD_14
	,SALDO_FX_ENT_21
	,SALDO_PDD_21
	,SALDO_FX_ENT_25
	,SALDO_PDD_25
	,RECEBIVEL
	--,ID_SEGMENTO
FROM [DB_SISCOB].[APP_EXCEL].[VW_RELATORIO_WEB_MIS_SEGMENTO_TODOS]
WHERE 
	SEG_DESCR LIKE ('VPE%')
AND
	TASK_FORCE = 'DEMAIS'









GO


