USE [DB_G_CASH_BBRIL]
GO

/****** Object:  Table [sch_Auxiliar].[Tbl_Area_Ofensora]    Script Date: 4/24/2017 4:44:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [sch_Auxiliar].[Tbl_Area_Ofensora](
	[ID_AREA] [int] IDENTITY(1,1) NOT NULL,
	[AREA_OFENSORA] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_AREA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


