USE [DB_G_CASH_BBRIL]
GO

/****** Object:  Table [sch_Adm].[Tbl_Controle_Car]    Script Date: 4/24/2017 4:41:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [sch_Adm].[Tbl_Controle_Car](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PROCESSO_CAR] [varchar](255) NOT NULL,
	[NOME_ARQUIVO] [varchar](255) NOT NULL,
	[CAR_PERIODO] [char](2) NOT NULL,
	[STATUS] [int] NULL,
	[DT_PROCESSAMENTO] [datetime] NULL,
	[DT_PROCESSAMENTO_FIM] [datetime] NULL,
 CONSTRAINT [PK_TB_APP_CONTROLE_CAR] PRIMARY KEY CLUSTERED 
(
	[ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


