USE [DB_G_CASH_BBRIL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--CASO A TABELA NÃO EXISTA, ELA SERÁ CRIADA
--DROP TABLE [sch_Carga].[Tbl_Cargas_Origens_Destinos]
IF OBJECT_ID('[sch_Carga].[Tbl_Cargas_Origens_Destinos]') IS NULL
BEGIN
		CREATE TABLE [sch_Carga].[Tbl_Cargas_Origens_Destinos](
			[COD_EMPRESA]		INT NOT NULL,
			[ATIVO]				BIT NOT NULL,
			[TIPO_CARGA]		VARCHAR(50) NOT NULL,
			[CARGA_ORIGEM]		VARCHAR(200) NOT NULL, --'C:\CARGA\'
			[NOME_ABA]			VARCHAR(50)  NULL, --'CAR_BRIL' -- 'CAR_BOMBRIL'
			[CARGA_DESTINO]		VARCHAR(200) NOT NULL,--[SCH_CARGA].TBL_IMPORT_CAR_BRIL_temp
			[OPERACAO]			VARCHAR(50) NOT NULL,--'INSERT',
		PRIMARY KEY CLUSTERED 
(
	[COD_EMPRESA],[TIPO_CARGA]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


	
END
GO