USE [DB_G_CASH_BBRIL]
GO

/****** Object:  Table [sch_Principal].[Tbl_Historico]    Script Date: 4/24/2017 4:48:20 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [sch_Principal].[Tbl_Historico](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_CONSOLIDADO] [bigint] NOT NULL,
	[ID_FOCO_FEEDBACK] [int] NULL,
	[ID_TIPO_PAGAMENTO] [int] NULL,
	[ID_ANALISTA] [int] NULL,
	[TIME_STAMP] [datetime] NULL,
	[DT_CONTATO] [date] NULL,
	[DT_FOLLOW] [date] NULL,
	[RESPONSAVEL] [varchar](255) NULL,
	[HISTORICO_DETALHADO] [varchar](5000) NULL,
	[RE_PROBLEMA] [varchar](1000) NULL,
	[RE_ACAO] [varchar](1000) NULL,
	[OBS] [varchar](1) NULL,
	[MES_ATUALIZACAO] [int] NULL,
	[STATUS] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


