USE DB_G_CASH_BBRIL

	--DROP TABLE [SCH_CARGA].TBL_CARGA_log
	IF OBJECT_ID('[SCH_CARGA].TBL_CARGA_log') IS NULL
	BEGIN
		CREATE TABLE [SCH_CARGA].TBL_CARGA_log (
		ID				INT IDENTITY(1, 1) NOT NULL,
		DT_CARGA		DATETIME DEFAULT GETDATE() NOT NULL,
		[Login]			VARCHAR(100) NOT NULL,
		Hostname		VARCHAR(100) NOT NULL,

		QTD_REGISTROS	INT,
		VALOR_MI_POS	DECIMAL(18, 2),
		VALOR_MI_NEG	DECIMAL(18, 2),
		VALOR_MI_TOTAL	DECIMAL(18, 2),
		VALOR_MI_OK		BIT,
		OPERACAO		VARCHAR(50),
		TABELA_CARGA	VARCHAR(100),
		
		CONSTRAINT [PK_TBL_IMPORT_CAR_BRIL_log] PRIMARY KEY CLUSTERED 
(
	[ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

	END