USE [DB_G_CASH_BBRIL]
GO

/****** Object:  Table [sch_Auxiliar].[Tbl_Task_Force]    Script Date: 4/24/2017 4:46:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [sch_Auxiliar].[Tbl_Task_Force](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DESCRICAO_TASK] [varchar](100) NULL,
 CONSTRAINT [PK_TB_TASK_FORCE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


